spring.application.name=Store

nasa.api.key=4loT4Bo1hSX00nAyo1efdefMj0Z6dBWqEso0yjSI

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Render port
server.port=${PORT:8080}

# Static images (container path)
spring.mvc.static-path-pattern=/apod-images/**
spring.web.resources.static-locations=file:/app/apod-images/

# Image storage directory
image.dir=/app/apod-images/