spring.application.name=Store

nasa.api.key=4loT4Bo1hSX00nAyo1efdefMj0Z6dBWqEso0yjSI

spring.mvc.static-path-pattern=/apod-images/**
spring.web.resources.static-locations=file:/C:/Users/Sid/OneDrive/Desktop/Store/Store/apod-images/
image.dir=/app/apod-images/

server.port=${PORT:8080}