spring.application.name=Store
spring.datasource.url=jdbc:postgresql://localhost:5432/Users
spring.datasource.username=postgres
spring.datasource.password=Siddhesh@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.static-path-pattern=/apod-images/**
spring.web.resources.static-locations=file:/C:/Users/Sid/OneDrive/Desktop/Store/Store/apod-images/
